config/routes.rb
Myapp::Application.routes.draw do
  get "home/Login_form"

resources :homes 
resources :doner_registration_forms
resources :donnie_registration_forms

get "contribute/home"
get "contribute/about_us"
get "contribute/donate"
get "contribute/gallery"
get "contribute/contact_us"
get "contribute/blog"
get "contribute/faq"

get "home/index"
get "home/donnie_registration_form"
get "home/doner_registration_form"

get "home/children"
get "home/education"
get "home/employment"
get "home/youth"
get "home/elderly"
get "home/disabled"
get "home/women"
get "home/health"
get "home/book"
get "home/medicine"
get "home/stationery"
get "home/money"
get "home/care"
get "home/cloth"
get "home/computer"
get "home/bed"
get "home/bedsheet"
get "home/mechanical_toolkit"
get "home/service"
get "home/vehicle"
get "home/raw_food"
get "home/stitching_machine"
get "home/medical_equipment"
get "home/toy"

get "about_us/what_we_do"
get "about_us/how_it_works"
get "about_us/our_mission"
get "about_us/our_achievments"
get "about_us/how_you_can_contribute"
get "about_us/read_more"

get "donate/organization_prakalp"
get "donate/donation_form"
get "donate/what_to_donate"
get "donate/how_to_donate"

get "gallery/image"
get "gallery/video"

get "doner_registration_form/show"
get "doner_registration_form/new"
get "doner_registration_form/doner_profile"
get "donnie_registration_form/prakalp_profile"
get "donnie_registration_form/show"
get "donnie_registration_form/new"

match 'about_us_contributes' => "Contribute#about_us"
match 'donate_contributes' => "Contribute#donate"
match 'gallery_contributes' => "Contribute#gallery"
match 'contact_us_contributes' => "Contribute#contact_us"
match 'blog_contributes' => "Contribute#blog"
match 'faq_contributes' => "Contribute#faq"
match 'home_contributes' => "Contribute#home"

match 'donnie_registration_form_homes' => "Home#donnie_registration_form"
match 'doner_registration_form_homes' => "Home#doner_registration_form"

match 'women_homes' => "Home#women"
match 'health_homes' => "Home#health"
match 'education_homes' => "Home#education"
match 'employment_homes' => "Home#employment"
match 'disabled_homes' => "Home#disabled"
match 'elderly_homes' => "Home#elderly"
match 'children_homes' => "Home#children"
match 'youth_homes' => "Home#youth"
match 'care_homes' => "Home#care"
match 'computer_homes' => "Home#computer"
match 'service_homes' => "Home#service"
match 'book_homes' => "Home#book"
match 'money_homes' => "Home#money"
match 'raw_food_homes' => "Home#raw_food"
match 'stitching_machine_homes' => "Home#stitching_machine"
match 'medicine_homes' => "Home#medicine"
match 'medical_equipment_homes' => "Home#medical_equipment"
match 'bed_homes' => "Home#bed"
match 'bedsheet_homes' => "Home#bedsheet"
match 'vehicle_homes' => "Home#vehicle"
match 'stationery_homes' => "Home#stationery"
match 'cloth_homes' => "Home#cloth"
match 'mechanical_toolkit_homes' => "Home#mechanical_toolkit"
match 'toy_homes' => "Home#toy"

match 'show_doner_registration_forms' => "DonerRegistrationForms#show"
match 'new_doner_registration_forms' => "DonerRegistrationForms#new"
match 'doner_profile_doner_registration_forms' => "DonerRegistrationForms#doner_profile"
match 'prakalp_profile_donnie_registration_forms' => "DonnieRegistrationForms#prakalp_profile"
match 'show_donnie_registration_forms' => "DonnieRegistrationForms#show"
match 'new_donnie_registration_forms' => "DonnieRegistrationForms#new"

match 'what_we_do_about_us' => "AboutUs#what_we_do"
match 'how_it_works_about_us' => "AboutUs#how_it_works"
match 'our_mission_about_us' => "AboutUs#our_mission"
match 'our_achievments_about_us' => "AboutUs#our_achievments"
match 'how_you_can_contribute_about_us' => "AboutUs#how_you_can_contribute"
match 'read_more_about_us' => "AboutUs#read_more"

match 'organization_prakalp_donates' => "Donate#organization_prakalp"
match 'donation_form_donates' => "Donate#donation_form"
match 'what_to_donate_donates' => "Donate#what_to_donate"
match 'how_to_donate_donates' => "Donate#how_to_donate"

match 'image_galleries' => "Gallery#image"
match 'video_galleries' => "Gallery#video"

  root :to => "contribute#home"

end

app/models/about_us.rb
class AboutUs < ActiveRecord::Base
end

app/models/contact_us.rb
class ContactUs < ActiveRecord::Base
end

app/models/contribute.rb
class Contribute < ActiveRecord::Base
end

app/models/donate.rb
class Donate < ActiveRecord::Base
end

app/models/faq.rb
class Faq < ActiveRecord::Base
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
end

app/models/home.rb
class Home < ActiveRecord::Base
  belongs_to :doner_registration_form
  belongs_to :login_form
end

app/models/login_form.rb
class LoginForm < ActiveRecord::Base
  belongs_to :home
end

app/controllers/contribute_controller.rb
class ContributeController < ApplicationController
  def home
  end
  
  def about_us
  end

  def donate
  end

  def gallery
  end

  def contact_us
  end

  def blog
  end

  def faq
  end

end

app/controllers/donate_controller.rb
class DonateController < ApplicationController
   def organization_prakalp
   end
   
   def donation_form
   end

   def what_to_donate
   end

   def how_to_donate
   end
end

app/controllers/faq_controller.rb
class FaqController < ApplicationController
end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
  def image
  end

  def video
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def Login_form
    @form3=LoginForm.new
    respond_to do |f|
	  f.html
	  f.xml { render :xml => @form3 }
	end

  end

  def index
  end
 
  def doner_profile
  end
  
  def prakalp_profile
  end

  def donnie_registration_form
   @form2=DonnieRegistrationForm.new
    respond_to do |f|
	  f.html
	  f.xml { render :xml => @form2 }
	end
  end
  
  def doner_registration_form
   @form1=DonerRegistrationForm.new
     respond_to do |f|
	    f.html
	    f.xml { render :xml => @form1 }
     end
  end

  def children
  end

  def youth
  end

  def disabled
  end

  def women
  end

  def health
  end

  def education
  end

  def employment
  end

  def care
  end

  def elderly
  end

  def medicine
  end

  def book
  end

  def stationery
  end

  def computer
  end

  def money
  end

  def bed
  end

  def bedsheet
  end

  def medical_equipment
  end

  def raw_food
  end

  def vehicle
  end

  def stitching_machine
  end

  def service
  end

  def mechanical_toolkit
  end

  def cloth
  end

  def toy
  end

  
end

app/helpers/about_us_helper.rb
module AboutUsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_us_helper.rb
module ContactUsHelper
end

app/helpers/contribute_helper.rb
module ContributeHelper
end

app/helpers/donate_helper.rb
module DonateHelper
end

app/helpers/donnie_helper.rb
module DonnieHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_form_helper.rb
module LoginFormHelper
end

app/views/contribute/home.html.erb
    
 <div id="subdivision1content" style="text-align:left;height:700px;width:200px;float:left;">
<b>Choose a Cause to Donate<b>
<ul id="verticalmenu" class="glossymenu">
     <li><%= link_to "Children", children_homes_path %>
          <ul id="verticalmenu" class="glossymenu">
                     <li><%= link_to "Services", service_homes_path %></li>
                     <li><%= link_to "Care", care_homes_path %></li>
                     <li><%= link_to "Clothes", cloth_homes_path %></li>
                     <li><%= link_to "Books", book_homes_path %></li>
	                 <li><%= link_to "Stationery", stationery_homes_path %></li>
                     <li><%= link_to "Medicines", medicine_homes_path %></li>
                     <li><%= link_to "Toys", toy_homes_path %></li>
		 </ul>
    </li>
    <li><%= link_to "Youth", youth_homes_path %>
         <ul id="verticalmenu" class="glossymenu">
        			 <li><%= link_to "Services", service_homes_path %></li>
        			 <li><%= link_to "Books", book_homes_path %></li>
					 <li><%= link_to "Mechanical Toolkit", mechanical_toolkit_homes_path %></li>
					 <li><%= link_to "Money", money_homes_path %></li>
					 <li><%= link_to "Stationery", stationery_homes_path %></li>
					 <li><%= link_to "Vehicle", vehicle_homes_path %></li>
					 <li><%= link_to "Computers", computer_homes_path %></li>
		 </ul>

    </li>
    <li><%= link_to "Disabled", disabled_homes_path %>
         <ul id="verticalmenu" class="glossymenu">
        			 <li><%= link_to "Services", service_homes_path %></li>
        			 <li><%= link_to "Money", money_homes_path %></li>
					 <li><%= link_to "Mechanical Toolkit", mechanical_toolkit_homes_path %></li>
					 <li><%= link_to "Clothes", cloth_homes_path %></li>
					 <li><%= link_to "Stationery", stationery_homes_path %></li>
					 <li><%= link_to "Vehicle", vehicle_homes_path %></li>
		 </ul>
    </li>
    <li><%= link_to "Elderly", elderly_homes_path %>
         <ul id="verticalmenu" class="glossymenu">
        			 <li><%= link_to "Services", service_homes_path %></li>
        			 <li><%= link_to "Raw Food", raw_food_homes_path %></li>
					 <li><%= link_to "Medicines", medicine_homes_path %></li>
					 <li><%= link_to "Money", money_homes_path %></li>
					 <li><%= link_to "Clothes", cloth_homes_path %></li>
		 </ul>
    </li>
    <li><%= link_to "Women", women_homes_path %>
         <ul id="verticalmenu" class="glossymenu">
        			 <li><%= link_to "Services", service_homes_path %></li>
        			 <li><%= link_to "Raw Food", raw_food_homes_path %></li>
					 <li><%= link_to "Clothes", cloth_homes_path %></li>
					 <li><%= link_to "Books", book_homes_path %></li>
					 <li><%= link_to "Stationery", stationery_homes_path %></li>
					 <li><%= link_to "Medicines", medicine_homes_path %></li>
					 <li><%= link_to "Stitching Machine", stitching_machine_homes_path %></li>
					 <li><%= link_to "Computers", computer_homes_path %></li>
		 </ul>
    </li>
    <li><%= link_to "Health", women_homes_path %>
         <ul id="verticalmenu" class="glossymenu">
        			 <li><%= link_to "Services", service_homes_path %></li>
        			 <li><%= link_to "Raw Food", raw_food_homes_path %></li>
					 <li><%= link_to "Clothes", cloth_homes_path %></li>
					 <li><%= link_to "Beds", bed_homes_path %></li>
					 <li><%= link_to "Medical Equipments", medical_equipment_homes_path %></li>
					 <li><%= link_to "Medicines", medicine_homes_path %></li>
					 <li><%= link_to "Bedsheets", bedsheet_homes_path %></li>
					 <li><%= link_to "Computers", computer_homes_path %></li>
		 </ul>
    </li>
    <li><%= link_to "Care", care_homes_path %>
         <ul id="verticalmenu" class="glossymenu">
        			 <li><%= link_to "Services", service_homes_path %></li>
        			 <li><%= link_to "Raw Food", raw_food_homes_path %></li>
					 <li><%= link_to "Clothes", cloth_homes_path %></li>
					 <li><%= link_to "Books", book_homes_path %></li>
					 <li><%= link_to "Stationery", stationery_homes_path %></li>
					 <li><%= link_to "Medicines", medicine_homes_path %></li>
		 </ul>
    </li>
    <li><%= link_to "Education", education_homes_path %>
         <ul id="verticalmenu" class="glossymenu">
        			 <li><%= link_to "Services", service_homes_path %></li>
					 <li><%= link_to "Books", book_homes_path %></li>
					 <li><%= link_to "Stationery", stationery_homes_path %></li>
					 <li><%= link_to "Medicines", medicine_homes_path %></li>
					 <li><%= link_to "Computers", computer_homes_path %></li>
		 </ul>
    </li>
    <li><%= link_to "Employment", employment_homes_path %>
         <ul id="verticalmenu" class="glossymenu">
        			 <li><%= link_to "Services", service_homes_path %></li>
					 <li><%= link_to "Books", book_homes_path %></li>
					 <li><%= link_to "Stationery", stationery_homes_path %></li>
					 <li><%= link_to "Medicines", medicine_homes_path %></li>
					 <li><%= link_to "Computers", computer_homes_path %></li>
					 <li><%= link_to "Mechanical Toolkit", mechanical_toolkit_homes_path %></li>
         </ul>
    </li>
 </ul>
</div>   

<div id="subdivision2content" style="text-align:left;height:700px;width:600px;float:left;" name="subdivision2">
<div id="carousel" height="450" width="550">
	
	<div id="slides" height="280" > 
		<ul>
			<li><img src="images/RSS.jpg" width="550" height="280" alt="Slide 1" /><caption>Organi</caption></li>
			<li><img src="images/gaurav.png" width="550" height="280" alt="Slide 2"/></li>
			<li><img src="images/HelpAgeIndia.preview.jpg" width="550" height="280" alt="Slide 3"/></li>
            <li><img src="images/disha.jpg" width="550" height="280" alt="Slide 4"/></li>
		</ul>
		<div class="clear"></div>
	</div>
        <div id="buttons" height="100">
		     <a href="#" id="prev">Previous</a>
			 <a href="#" id="next">Next</a>
		<div class="clear"></div>
	</div>
	<div class="clear"></div>
</div>
<div id="subdivision2content2" style="text-align:left;height:250px;width:550px;float:left;" name="subdivision2">
<div id="Updates" style="height:200px;width:120px;float:left; color:black;">   
   <ul>
       <li> update1</li>
       <li> update2</li>
       <li> update3</li>
       <li> update4</li>
   </ul>    
      
</div>
          
<div id="Summary" style="height:200px;width:430px;float:left;color:black;">
        Contribute For A Cause
   
       <article>
       
           A donation is a gift given by physical or legal persons, typically for charitable    purposes and/or to benefit a cause. A donation may take various forms, including cash, services, new or used goods       including    clothing, toys, food, and vehicles. It also may consist of emergency, relief or humanitarian aid items, development aid    support, and can also relate to medical care needs as i.e. blood or organs for transplant. Charitable gifts of goods or    services are also called gifts in kind.   
       This platform provides a mean to connect donator to needy people in a    broad    area.   
       
          </article>
</div>

</div>
</div>

<div id="subdivision3content" style="text-align:left;height:700px;width:200px;float:left;">   

<form>
<pre>
Login Form:
User name: <input type="text" value="" size="10" id=""/>

Password: <input type="password" value="" size="10" id=""/>

<input type="submit" value="Sign In" size="10" id=""/>     <input type="reset" value="Clear" size="10" id=""/>

<a href="forgot.html">forgot your password</a>

<%= link_to "New Doner? Sign Up", doner_registration_form_homes_path %>
<%= link_to "New Prakalp? Sign Up", donnie_registration_form_homes_path %>
</pre>
</form>

<form>
<pre>
Enquiry Form:

Name: 
<input type="text" value="" size="20" id="1"/>

Email Id:  
<input type="email" size="20" maxlength="10" id="2"/>

Subject:
<input type="text" size="20" id="3"/>

Category: 
<select id="4">
<option> doner</option>
<option> doniee</option>
</select>

Query: 
<input type="text" size="20" id="5"/>
</pre>
</form>														
<div class='spread'>
  <div class='twshare left'>
    <a href="http://twitter.com/share" class="twitter-share-button" data-count="horizontal" data-via="funonrails">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
  </div>
  <script src="http://connect.facebook.net/en_US/all.js#xfbml=1"></script><fb:like href="" layout="button_count" show_faces="false" width="450" font=""></fb:like>
</div>

</div>

<div id="division4ads" style="text-align:left;height:200px;width:1000px;">
    
   <div id="Ad1" style="background-color:dimgray;height:200px;width:300px;float:left;">Advertisement 1
   <img src="C:\Documents and Settings\user\My Documents\My Pictures\image3.png" height="200" width="300"/>
   </div>
   <div id="Ad2" style="background-color:thistle;height:200px;width:400px;float:left;">Advertisement 2
   <img src="C:\Documents and Settings\user\My Documents\My Pictures\image2.jpg" height="190" width="400"/></div>
   <div id="Ad3" style="background-color:rosybrown;height:200px;width:300px;float:left;">Advertisement 3
   <img src="C:\Documents and Settings\user\My Documents\My Pictures\image4.jpg" height="190" width="300"/></div>
    
</div> 

<div id="division5footer" style="text-align:left;height:40px;width:1000px;">
copyright@2011DonatetoPeople.org. All Rights Reserved <a href="disclaimer"> Disclaimer</a> <a href="sitemap"> Sitemap</a>
</div> 

app/views/contribute/slide.html.erb
<div id="carousel" height="300" width="550">
	
	<div id="slides" > 
		<ul>
			<li><img src="images/RSS.jpg" width="550" height="300" alt="Slide 1" /><caption>Organi</caption></li>
			<li><img src="images/gaurav.png" width="550" height="300" alt="Slide 2"/></li>
			<li><img src="images/HelpAgeIndia.preview.jpg" width="550" height="300" alt="Slide 3"/></li>
                        <li><img src="images/disha.jpg" width="550" height="300" alt="Slide 4"/></li>
		</ul>
		<div class="clear"></div>
	</div>
        <div id="buttons">
		     <a href="#" id="prev">prev</a>
		<a href="#" id="next">next</a>
		<div class="clear"></div>
	</div>
	<div class="clear"></div>
</div>
 
 
<iframe src="subdivision2content.html" style="text-align:left;height:250px;width:550px;float:left;" name="subdivision2">
</iframe>
