config/routes.rb
Myapp::Application.routes.draw do
  get "home/Login_form"

resources :homes 
resources :doner_registration_forms
resources :donnie_registration_forms

get "contribute/home"
get "contribute/about_us"
get "contribute/donate"
get "contribute/gallery"
get "contribute/contact_us"
get "contribute/blog"
get "contribute/faq"

get "home/index"
get "home/donnie_registration_form"
get "home/doner_registration_form"

get "home/children"
get "home/education"
get "home/employment"
get "home/youth"
get "home/elderly"
get "home/disabled"
get "home/women"
get "home/health"
get "home/book"
get "home/medicine"
get "home/stationery"
get "home/money"
get "home/care"
get "home/cloth"
get "home/computer"
get "home/bed"
get "home/bedsheet"
get "home/mechanical_toolkit"
get "home/service"
get "home/vehicle"
get "home/raw_food"
get "home/stitching_machine"
get "home/medical_equipment"
get "home/toy"

get "about_us/what_we_do"
get "about_us/how_it_works"
get "about_us/our_mission"
get "about_us/our_achievments"
get "about_us/how_you_can_contribute"
get "about_us/read_more"

get "donate/organization_prakalp"
get "donate/donation_form"
get "donate/what_to_donate"
get "donate/how_to_donate"

get "gallery/image"
get "gallery/video"

get "doner_registration_form/show"
get "doner_registration_form/new"
get "doner_registration_form/doner_profile"
get "donnie_registration_form/prakalp_profile"
get "donnie_registration_form/show"
get "donnie_registration_form/new"

match 'about_us_contributes' => "Contribute#about_us"
match 'donate_contributes' => "Contribute#donate"
match 'gallery_contributes' => "Contribute#gallery"
match 'contact_us_contributes' => "Contribute#contact_us"
match 'blog_contributes' => "Contribute#blog"
match 'faq_contributes' => "Contribute#faq"
match 'home_contributes' => "Contribute#home"

match 'donnie_registration_form_homes' => "Home#donnie_registration_form"
match 'doner_registration_form_homes' => "Home#doner_registration_form"

match 'women_homes' => "Home#women"
match 'health_homes' => "Home#health"
match 'education_homes' => "Home#education"
match 'employment_homes' => "Home#employment"
match 'disabled_homes' => "Home#disabled"
match 'elderly_homes' => "Home#elderly"
match 'children_homes' => "Home#children"
match 'youth_homes' => "Home#youth"
match 'care_homes' => "Home#care"
match 'computer_homes' => "Home#computer"
match 'service_homes' => "Home#service"
match 'book_homes' => "Home#book"
match 'money_homes' => "Home#money"
match 'raw_food_homes' => "Home#raw_food"
match 'stitching_machine_homes' => "Home#stitching_machine"
match 'medicine_homes' => "Home#medicine"
match 'medical_equipment_homes' => "Home#medical_equipment"
match 'bed_homes' => "Home#bed"
match 'bedsheet_homes' => "Home#bedsheet"
match 'vehicle_homes' => "Home#vehicle"
match 'stationery_homes' => "Home#stationery"
match 'cloth_homes' => "Home#cloth"
match 'mechanical_toolkit_homes' => "Home#mechanical_toolkit"
match 'toy_homes' => "Home#toy"

match 'show_doner_registration_forms' => "DonerRegistrationForms#show"
match 'new_doner_registration_forms' => "DonerRegistrationForms#new"
match 'doner_profile_doner_registration_forms' => "DonerRegistrationForms#doner_profile"
match 'prakalp_profile_donnie_registration_forms' => "DonnieRegistrationForms#prakalp_profile"
match 'show_donnie_registration_forms' => "DonnieRegistrationForms#show"
match 'new_donnie_registration_forms' => "DonnieRegistrationForms#new"

match 'what_we_do_about_us' => "AboutUs#what_we_do"
match 'how_it_works_about_us' => "AboutUs#how_it_works"
match 'our_mission_about_us' => "AboutUs#our_mission"
match 'our_achievments_about_us' => "AboutUs#our_achievments"
match 'how_you_can_contribute_about_us' => "AboutUs#how_you_can_contribute"
match 'read_more_about_us' => "AboutUs#read_more"

match 'organization_prakalp_donates' => "Donate#organization_prakalp"
match 'donation_form_donates' => "Donate#donation_form"
match 'what_to_donate_donates' => "Donate#what_to_donate"
match 'how_to_donate_donates' => "Donate#how_to_donate"

match 'image_galleries' => "Gallery#image"
match 'video_galleries' => "Gallery#video"

  root :to => "contribute#home"

end

app/models/about_us.rb
class AboutUs < ActiveRecord::Base
end

app/models/contact_us.rb
class ContactUs < ActiveRecord::Base
end

app/models/contribute.rb
class Contribute < ActiveRecord::Base
end

app/models/donate.rb
class Donate < ActiveRecord::Base
end

app/models/faq.rb
class Faq < ActiveRecord::Base
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
end

app/models/home.rb
class Home < ActiveRecord::Base
  belongs_to :doner_registration_form
  belongs_to :login_form
end

app/models/login_form.rb
class LoginForm < ActiveRecord::Base
  belongs_to :home
end

app/controllers/faq_controller.rb
class FaqController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def Login_form
    @form3=LoginForm.new
    respond_to do |f|
	  f.html
	  f.xml { render :xml => @form3 }
	end

  end

  def index
  end
 
  def doner_profile
  end
  
  def prakalp_profile
  end

  def donnie_registration_form
   @form2=DonnieRegistrationForm.new
    respond_to do |f|
	  f.html
	  f.xml { render :xml => @form2 }
	end
  end
  
  def doner_registration_form
   @form1=DonerRegistrationForm.new
     respond_to do |f|
	    f.html
	    f.xml { render :xml => @form1 }
     end
  end

  def children
  end

  def youth
  end

  def disabled
  end

  def women
  end

  def health
  end

  def education
  end

  def employment
  end

  def care
  end

  def elderly
  end

  def medicine
  end

  def book
  end

  def stationery
  end

  def computer
  end

  def money
  end

  def bed
  end

  def bedsheet
  end

  def medical_equipment
  end

  def raw_food
  end

  def vehicle
  end

  def stitching_machine
  end

  def service
  end

  def mechanical_toolkit
  end

  def cloth
  end

  def toy
  end

  
end

app/helpers/about_us_helper.rb
module AboutUsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_us_helper.rb
module ContactUsHelper
end

app/helpers/contribute_helper.rb
module ContributeHelper
end

app/helpers/donate_helper.rb
module DonateHelper
end

app/helpers/donnie_helper.rb
module DonnieHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_form_helper.rb
module LoginFormHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myapp</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

<script type="text/javascript" src="javascripts/jquery.js"></script>
<script type="text/javascript" src="javascripts/menu.js"></script>

<script type="text/javascript">
$(document).ready(function() {

	//rotation speed and timer
	var speed = 5000;
	var run = setInterval('rotate()', speed);	
	
	//grab the width and calculate left value
	var item_width = $('#slides li').outerWidth(); 
	var left_value = item_width * (-1); 
        
    //move the last item before first item, just in case user click prev button
	$('#slides li:first').before($('#slides li:last'));
	
	//set the default item to the correct position 
	$('#slides ul').css({'left' : left_value});

    //if user clicked on prev button
	$('#prev').click(function() {

		//get the right position            
		var left_indent = parseInt($('#slides ul').css('left')) + item_width;

		//slide the item            
		$('#slides ul:not(:animated)').animate({'left' : left_indent}, 200,function(){    

            //move the last item and put it as first item            	
			$('#slides li:first').before($('#slides li:last'));           

			//set the default item to correct position
			$('#slides ul').css({'left' : left_value});
		
		});

		//cancel the link behavior            
		return false;
            
	});

 
    //if user clicked on next button
	$('#next').click(function() {
		
		//get the right position
		var left_indent = parseInt($('#slides ul').css('left')) - item_width;
		
		//slide the item
		$('#slides ul:not(:animated)').animate({'left' : left_indent}, 200, function () {
            
            //move the first item and put it as last item
			$('#slides li:last').after($('#slides li:first'));                 	
			
			//set the default item to correct position
			$('#slides ul').css({'left' : left_value});
		
		});
		         
		//cancel the link behavior
		return false;
		
	});        
	
	//if mouse hover, pause the auto rotation, otherwise rotate it
	$('#slides').hover(
		
		function() {
			clearInterval(run);
		}, 
		function() {
			run = setInterval('rotate()', speed);	
		}
	); 
        
});

//a simple function to click next link
//a timer will call this function, and the rotation will begin :)  
function rotate() {
	$('#next').click();
}

</script>

<script type="text/javascript" src="./vtip.js"></script>
<link rel="stylesheet" type="text/css" href="javascripts/js/plugins/buttonCaptcha/jquery.buttonCaptcha.styles.css" />

<script type="text/javascript" language="javascript" src="javascripts/js/jquery/jquery-1.5.1.min.js"></script>
<script type="text/javascript" language="javascript" src="javascripts/js/jquery/jquery-ui-1.8.10.custom.min.js"></script>
<script type="text/javascript" language="javascript" src="javascripts/js/plugins/buttonCaptcha/jquery.buttonCaptcha.min.js"></script>

  <%= stylesheet_link_tag :all %>
  <%= csrf_meta_tag %>
</head>
<body id="body1" style="background-image:url(images/back.jpg);">
      
<div id="divisionmain" style="text-align:left;">
        
<div id="division1header" style="text-align:left;height:185px;width:1000px;padding-top:1%;">
 <img src="images/images.jpeg" width="100" height="100" style="float:left;"border="3">
 <h1 style="color:black;text-align:left;font-weight:700;font-size:300%;font-family:arial; margin:0;">Contribute For A Cause</h1>
 <h2 style="color:black; text-align:left;font-size:150%;">World's Largest Contribution Service</h2>  

<marquee scroll-amount="80" style="color:brown;dirtection:left;width:1000px;font-family:arial;">Providing Help To The Needy People</marquee>
   
</div>

<div id="division2pages" style="text-align:left;height:45px;width:1000px;padding-bottom:35px; padding-left:0px;">
   
   <nav style="margin-left:0;">
<ul class="dropdown">
        	

<li><%= link_to "Home", home_contributes_path %>


     <li><%= link_to "About Us", about_us_contributes_path %>
                        <ul class="sub_menu">
        			 <li><%= link_to "What We Do", what_we_do_about_us_path %></li>
        			 <li><%= link_to "How It Works", how_it_works_about_us_path %></li>
        			
        			 <li><%= link_to "Our Mission", our_mission_about_us_path %></li>
        			 <li><%= link_to "Our Achievements", our_achievments_about_us_path %></li>
        			 
        			 <li><%= link_to "How You Can Contribute", how_you_can_contribute_about_us_path %></li>
        			 <li><%= link_to "Read More", read_more_about_us_path %></li>
        			 
        		</ul>
     </li>
     <li> <%= link_to "Donate", donate_contributes_path %>
                        <ul class="sub_menu">
							 <li><%= link_to "Organizations & Prakalps", organization_prakalp_donates_path %></li>
							 <li><%= link_to "Donation Form", donation_form_donates_path %></li>
        			         <li><%= link_to "What to Donate", what_to_donate_donates_path %></li>
        			         <li><%= link_to "How to Donate", how_to_donate_donates_path %></li>
        			    </ul>
     </li>
     <li><%= link_to "Gallery", gallery_contributes_path %>
	                    <ul class="sub_menu">
							 <li><%= link_to "Images", image_galleries_path %></li>
							 <li><%= link_to "Videos", video_galleries_path %></li>
                        </ul>
	 </li>

  
     <li><%= link_to "Contact Us", contact_us_contributes_path %></li>

     <li> <%= link_to "Blog", blog_contributes_path %></li>
     
     <li><%= link_to "FAQ", faq_contributes_path %></li> </ul></nav>                             <form style="text-align:right;">Search <input type="search" name="search" value="" size="10" style="float:right;text-align:left;"></form>
   
    
</div>        


<div id="division3content" style="text-align:left;height:940px;width:1000px;">
<%= yield %>
</div>

</div>

</body>
</html>